<!-- ERREUR DE PAGE 404 -->
<meta name="robots" content="noindex" />
<main class="content">
    <div class="box404">
        <h1>"ERROR 404 !"</h1>
        <p id="timerPathHome"></p>
        <p class="center"><img src="<?= VIEW_PATH ?>images/tennis_error_404.jpg"></p>
    </div>
</main>

<!-- redirection à la page d'acceuil -->
<script type="text/javascript" src="<?= VIEW_PATH ?>js/404.js"></script>