<!-- FOOTER -->
<meta name="robots" content="noindex" />
<footer>
    <div id="licence">
        <div id="webmaster">
            <p>
                Le site Restaurant TCT a été mis à jour le 20 août 2018. Créé par M.Martinez Yoann pour l'association Tennis Club Toulonnais (var).<br>
                <span><i class="fas fa-copyright"></i> Copyright, </span> l’utilisation de notre site ne vous confère aucun droit de propriété intellectuelle sur nos prestations ni sur les contenus auxquels vous accédez.
                <a target="_blank" href="<?php htmlspecialchars(HOME) ?>?page=condition">Conditions d'utilisation</a><br>
                <a href="<?php htmlspecialchars(HOME) ?>?page=user/contact"><i class="fa fa-envelope"></i> Se désabonner de la news-letter.</a>
            </p>
        </div>
        <div id="reseau">
            <nav>
                <ul>
                    <li><h4>L'espace restauration </h4></li>
                    <li><a title="Espace restauration" class="logo_reseau" href="<?php htmlspecialchars(HOME) ?>?page=home"><i class="fas fa-home"></i> Accueil</a></li>
                    <li><a title="Carte du restaurant" class="logo_reseau" href="<?php htmlspecialchars(HOME) ?>?page=advice/view_advice"><i class="fas fa-comment-dots"></i> Les avis</a></li>

                </ul>
                <ul>
                    <li><h4>Prise de contact</h4></li>
                    <li><a class="logo_reseau" target="_blank" href="<?php htmlspecialchars(HOME) ?>?page=user/contact">Contactez-nous <i class="fa fa-envelope"></i></a></li>
                    <li><span class="logo_reseau">Tél : 04 94 14 12 90 <i class="fas fa-phone-square"></i></span></li>
                </ul>
                <ul>
                    <li><h4>Nos réseaux sociaux</h4></li>
                    <li><a title="rejoignez-nous sur facebook" class="logo_reseau" target="_blank" href="https://www.facebook.com/Tennis-club-toulonnais-1407133819341384/">Facebook <i class="fab fa-facebook-square"></i></a></li>

                    <li><a title="Club house du TCT" class="logo_reseau" target="_blank" href="https://ballejaune.com/club/TCT">Site web <img src=<?php htmlspecialchars(PATH_ROOT) ?>"<?= VIEW_PATH ?>icon/icon.jpg"></a></li>
            </nav>
        </div>
    </div>
</footer>