<!--------------------------- FORMULAIRE D'AJOUT DE PRODUIT ---------------------------------->
<main><meta name="robots" content="noindex" />
    <?php require_once "application/view/manager/boxNavManager.phtml" ?>

    <!-- ADD IMAGE -->
    <form id="ajout_form" method="post" action="<?="application/view/images/img_card/"?>upload.php" enctype="multipart/form-data">
        <fieldset>
            <legend><h2>Gestion des images</h2></legend>
            <div id="container_form">
                <h3>Ajouter une image liée à un produit</h3>
                <section class="box_register">
                    <ul>
                        <!-- PICTURE -->
                        <li>
                            <!-- On limite le fichier à 100Ko -->
                            <input type="hidden" name="MAX_FILE_SIZE" value="300000 ">Image à poster sur le serveur <em>"pas de caractères spéciaux, dimension requise (200 x 165), taille 40Ko max"</em> :
                            <input id="add_file" type="file" name="avatar"><input id="button_onform" type="submit" value="Envoyer">
                        </li>
                    </ul>
                </section>
        </fieldset>
    </form>

    <!-- ADD PRODUCT -->
    <form id="ajout_form" method="post">
        <fieldset>
            <legend><h2>Gestion des produits</h2></legend>
            <div id="container_form">
                <h3>Ajouter des produits</h3>
                <ul>
                    <section class="box_register"><!-- PICTURE -->
                        <li><label>Nom de l'image associé au menu <em>"précédemment téléchargée au-dessus"</em> :
                                <input type="text" id="Product" name="picture" placeholder="Hot-Dog.png"  required />
                            </label>
                        </li>

                        <!-- TITLE -->
                        <li>
                            <label>Titre :
                                <input type="text" id="Product" name="titleProduct" maxlength="50" placeholder="Hot-Dog..."  required />
                            </label>
                        </li>

                        <!-- DESCRIPTION -->
                        <li>
                            <label>Description :</label>
                            <textarea name="description" rows="10" cols="40" id="Product" maxlength="650" placeholder="Le typique sandwitch américain avec sa saucisse cuite accompagnée..." required></textarea>
                        </li>

                        <!-- PRIX -->
                        <li>
                            <label>Prix :
                                <input type="text" id="priceSingle" name="priceSingle" placeholder="20.90" maxlength="5" required />€
                            </label>
                        </li>

                        <!-- VALIDATE -->
                        <li class="form_title">
                            <button id="button_onform" type="submit" name="addProduct" >Ajouter le produit</button>
                        </li>
                    </section>
                </ul>
            </div>
        </fieldset>
    </form>

    <!-- Liste des produits -->
    <table class="table_list">
        <caption><h1>Carte du restaurant</h1></caption>
        <tbody>
        <?php foreach ($Products as $Product): ?>
            <tr>
                <td>
                    <img src="<?= VIEW_PATH ?>images/img_card/<?= $Product['picture'] ?>">
                </td>
                <td>
                    <h2><?= htmlspecialchars($Product['titleProduct']) ?></h2>
                    <p><?= htmlspecialchars($Product['description']) ?></p>
                </td>
                <td><span class="price"><?= number_format($Product['priceSingle'], 2) ?> €</span>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</main

