<meta name="robots" content="noindex" />
<div class="box_nav_manager">
    <div>
        <button class="manager_button"><i class="fas fa-arrow-alt-circle-left"></i></button>
    </div>
    <div>
        <a href="<?php HOME ?>?page=manager/cardManager"><i class="fas fa-plus-square"></i> Texte d'accueil et déroulant</a><br>
        <hr>
        <a href="<?php HOME ?>?page=manager/addProductManager"><i class="fas fa-plus-square"></i> Ajouter un produit</a>
        <hr>
        <a href="<?php HOME ?>?page=manager/operationProductManager"><i class="fas fa-plus-square"></i> Editer / supprimer un produit</a><br>
        <hr>
        <a href="<?php HOME ?>?page=manager/deleteAdviceManager"><i class="fas fa-plus-square"></i> Supprimer un avis</a><br>
        <hr>
        <a href="<?php HOME ?>?page=manager/listNewLetter"><i class="fas fa-plus-square"></i> Membres news-letter</a><br>
    </div>
</div>