<!-- PAGE D'ERREUR UPLOADE -->
<meta name="robots" content="noindex" />
<main class="content">
    <div class="box404">
        <h1>Echec de votre Upload !</h1>
        <h2>"Problèmes concernant votre ajout d'image !"</h2>
        <p id="timerPathHome"></p>
        <ol>
            <li>Vous devez uploader un fichier de type png, gif, jpg, jpeg, txt ou doc.</li>
            <li>Le fichier ne doit pas être trop volumineux ! <em> 40Ko Maximum.</em></li>
            <li>La dimension requis est : <em>(200 x 165).</em></li>
            <li>Ne doit pas contenir de <em>caractère spéciaux.</em></li>
        </ol>
        <input type="button" id="button_offform" value="Retour" onclick="window.location.href='<?php HOME ?>?page=manager/addProductManager'" />
    </div>
</main>


