<!-- VALIDATE UPLOADE -->
<meta name="robots" content="noindex" />
<main class="content">
    <div class="box404">
        <h1>Succes de votre Upload !</h1>
        <h2>Information concernant l'ajout de votre image !</h2>
        <p id="timerPathHome"></p>
        <p>L'Enregistrement a bien été effectué !</p>
        <p>Vous pouvez maintenant associer votre image à votre nouveau produit.</p>
        <p>Attention n'oubliez pas que pour le titre de votre image et d'inscrire le nom complet de l'image avec le type <em>".jpg, .png etc.."</em></p>
        <p>Exemple : nomduproduit<strong>.jpg</strong></p>
        <input type="button" id="button_offform" value="Retour" onclick="window.location.href='<?php HOME ?>?page=manager/addProductManager'" />
    </div>
</main>
